title: Anthony Hecht
author: Anthony Hecht
email: anthony@thestranger.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Anthony Hecht. There are others, but this one is me.

twitter_username: ahecht
github_username:  ahecht
keybase_username: ahecht
google_analytics: UA-399187-4

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
